---

- name: creating ec2 instances 
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    ami: ami-069aabeee6f53e7bf
  tasks:
    - amazon.aws.ec2_instance:
      name: "test ques"
      key_name: ansible-remote
      vpc_subnet_id: subnet-06c2fa1fd4ef2c35f
      instance_type: t2.micro
      security_group: default
      network:
        assign_public_ip: true
      image_id: ami-069aabeee6f53e7bf
      tags:
        Environment: Testing
